"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[[mgr.prepend_keymap]]
on   = [ "!" ]
run  = 'shell "$SHELL" --block'
desc = "Open shell here"

[[input.prepend_keymap]]
on   = [ "<Esc>" ]
run  = "close"
desc = "Cancel input"

# [[manager.prepend_keymap]]
# on = [ "l" ]
# run = "plugin augment-command --args='enter'"
# desc = "Enter a directory and skip directories with only a single subdirectory"

# [[manager.prepend_keymap]]
# on   = [ "S" ]
# run = "search --via=rga"
# desc = "Search files by content via ripgrep-all"

[[mgr.prepend_keymap]]
on   = "l"
run  = "plugin smart-enter"
desc = "Enter the child directory, or open the file"

[[mgr.prepend_keymap]]
on   = "T"
run  = "plugin --sync max-preview"
desc = "Maximize or restore preview"

[[mgr.prepend_keymap]]
on   = "F"
run  = "plugin smart-filter"
desc = "Smart filter"

# Use K to move up in the parent directory
[[mgr.prepend_keymap]]
on   = [ "K" ]
run  = [ "leave", "arrow -1", "enter" ]
desc = "Move up in the parent directory"

# Use J to move down in the parent directory
[[mgr.prepend_keymap]]
on   = [ "J" ]
run  = [ "leave", "arrow 1", "enter" ]
desc = "Move down in the parent directory"

[[mgr.prepend_keymap]]
on   = [ "<C-f>" ]
run  = "seek 5"
desc = "Seek down 5 units in the preview"

[[mgr.prepend_keymap]]
on   = [ "<C-b>" ]
run  = "seek -5"
desc = "Seek up 5 units in the preview"

[[mgr.prepend_keymap]]
on   = [ "g", "i" ]
run  = "plugin lazygit"
desc = "run lazygit"

[[mgr.prepend_keymap]]
on   = [ "g", "c" ]
run  = "plugin vcs-files"
desc = "Show Git file changes"

[[mgr.prepend_keymap]]
on = [ "g", "r" ]
run = '''
	shell 'ya emit cd --str "$(git rev-parse --show-toplevel)"'
'''
