Diagnostics:
  # Suppress: "*"
  Suppress: [undeclared_var_use, pp_file_not_found]
  Remove: modernize-use-trailing-return-type
  CheckOptions:
      WarnOnFloatingPointNarrowingConversion: false
  ClangTidy:
    CheckOptions:
      IgnoreMacros: true
      example-check.ExampleOption: 0
CompileFlags:
  Add: -ferror-limit=0
