Diagnostics:
  Limit: 1000
  Suppress: "*"
  # Suppress: [undeclared_var_use, pp_file_not_found]
  UnusedIncludes: "None"
  ClangTidy:
    Add: [modernize*, 'bugprone-*']
    Remove: modernize-use-trailing-return-type
    CheckOptions:
      IgnoreMacros: true
CompileFlags:
  Add: [-ferror-limit=0, -D__clangd__, -Wno-unknown-warning-option, ]
  Remove: [-march=*, -mabi=*, -mcpu=*,-mapcs,-mno-sched-prolog,
          -fno-ipa-sra,-mno-thumb-interwork,-fno-var-tracking-ssignments,-femit-struct-debug-baseonly,
          -fconserve-stack,-mthumb-interwork,-mword-relocations,
          -enable-trivial-auto-var-init-zero-knowing-it-will-be-removed-from-clang,
          -fno-allow-store-data-races,-fno-var-tracking-assignments,-mpc-relative-literal-loads,
          -forward-unknown-to-host-compiler, --expt-*, -gencode*, --generate-code*, -Xfatbin*,
          -arch=*, -rdc=*,-mstack-protector-guard*,-mbranch-protection*, ]
InlayHints:
  ParameterNames: true
  DeducedTypes: true
Index:
  Background: Build
