Diagnostics:
  Suppress: "*"
  UnusedIncludes: "None"
  # Suppress: [undeclared_var_use, pp_file_not_found]
  ClangTidy:
    Add: [modernize*, 'bugprone-*']
    Remove: modernize-use-trailing-return-type
    CheckOptions:
      IgnoreMacros: true

# Index:
#   Background: Skip
